// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Common {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SBmNvbW1vbiI4CgVFcnJvchIfCgRjb2RlGAEgASgO",
            "MhEuY29tbW9uLkVycm9yQ29kZRIOCgZkZXRhaWwYAiABKAkqTAoIR2FtZVR5",
            "cGUSDgoKR1RfVU5LTk9XThAAEg0KCUdUX0hPTERFTRABEg0KCUdUX0JBRFVH",
            "SRACEhIKDkdUX1NFVkVOX1BPS0VSEAMqgQQKCUVycm9yQ29kZRIICgRFX09L",
            "EAASDQoJRV9VTktOT1dOEAESFwoTRV9JTlZBTElEX1BBUkFNRVRFUhACEhQK",
            "EEVfSU5URVJOQUxfRVJST1IQAxIWChJFX0lOVkFMSURfVEFCTEVfSUQQChIS",
            "Cg5FX05PVF9JTl9UQUJMRRALEhcKE0VfTk9UX1BBUlRJQ0lQQVRJTkcQDBIT",
            "Cg9FX0lOVkFMSURfVE9LRU4QZBIXChNFX0lOVkFMSURfUk9PTV9UWVBFEG4S",
            "FQoRRV9JTlZBTElEX1JPT01fSUQQbxIVChFFX05PVF9FTk9VR0hfQ0hJUBBw",
            "EhQKEEVfSU5WQUxJRF9CVVlfSU4QcRIbChdFX1BMQVlFUl9BTFJFQURZX0VY",
            "SVNUUxByEhQKEEVfTk9fRU1QVFlfVEFCTEUQcxIUChBFX05PX0VNUFRZX0NI",
            "QUlSEHQSEAoMRV9MT1NTX0xJTUlUEHUSHgoZRV9OT19BQ1RJVkVfQkVUVElO",
            "R19ST1VORBCCARIVChBFX0lOVkFMSURfQUNUSU9OEIMBEhIKDUVfQ0FOTk9U",
            "X1ZPVEUQjAESHQoYRV9DQU5ESURBVEVfTk9UX0lOX1RBQkxFEI0BEhsKFkVf",
            "Tk9fQUNUSVZFX0RSQVdfUk9VTkQQlgESEwoORV9JTlZBTElEX0RSQVcQlwEq",
            "aQoKQWN0aW9uVHlwZRILCgdBVF9OT05FEAASCwoHQVRfRk9MRBABEgwKCEFU",
            "X0NIRUNLEAISCgoGQVRfQkVUEAMSCwoHQVRfQ0FMTBAEEgwKCEFUX1JBSVNF",
            "EAUSDAoIQVRfQUxMSU4QBiqiAQoLQmV0U2l6ZVR5cGUSCwoHQlNfTk9ORRAA",
            "EgsKB0JTX0ZPTEQQARIMCghCU19DSEVDSxACEgwKCEJTX0JCSU5HEAMSCwoH",
            "QlNfQ0FMTBAEEg4KCkJTX0REQURBTkcQBRINCglCU19RVUFURVIQBhILCgdC",
            "U19IQUxGEAcSDAoIQlNfQUxMSU4QCBIKCgZCU19NQVgQCRIKCgZCU19FTkQQ",
            "Cip4CgpLaWNrUmVhc29uEgsKB0tSX05PTkUQABILCgdLUl9WT1RFEAESCwoH",
            "S1JfQ0hJUBACEgsKB0tSX0xPU1MQAxISCg5LUl9NQUlOVEVOQU5DRRAEEg8K",
            "C0tSX0lOQUNUSVZFEAUSEQoNS1JfRElTQ09OTkVDVBAGYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Common.GameType), typeof(global::Common.ErrorCode), typeof(global::Common.ActionType), typeof(global::Common.BetSizeType), typeof(global::Common.KickReason), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Common.Error), global::Common.Error.Parser, new[]{ "Code", "Detail" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameType {
    [pbr::OriginalName("GT_UNKNOWN")] GtUnknown = 0,
    [pbr::OriginalName("GT_HOLDEM")] GtHoldem = 1,
    [pbr::OriginalName("GT_BADUGI")] GtBadugi = 2,
    [pbr::OriginalName("GT_SEVEN_POKER")] GtSevenPoker = 3,
  }

  public enum ErrorCode {
    /// <summary>
    /// 성공
    /// </summary>
    [pbr::OriginalName("E_OK")] EOk = 0,
    /// <summary>
    /// 알 수 없는 에러
    /// </summary>
    [pbr::OriginalName("E_UNKNOWN")] EUnknown = 1,
    /// <summary>
    /// 잘못된 파라미터일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_PARAMETER")] EInvalidParameter = 2,
    /// <summary>
    /// 서버 내부 에러(DB 에러 포함)
    /// </summary>
    [pbr::OriginalName("E_INTERNAL_ERROR")] EInternalError = 3,
    /// <summary>
    /// 잘못된 테이블ID로 요청 시
    /// </summary>
    [pbr::OriginalName("E_INVALID_TABLE_ID")] EInvalidTableId = 10,
    /// <summary>
    /// 해당 테이블에 없는데 요청 시
    /// </summary>
    [pbr::OriginalName("E_NOT_IN_TABLE")] ENotInTable = 11,
    /// <summary>
    /// 해당 테이블에서 게임에 참여 중이지 않는데 요청 시
    /// </summary>
    [pbr::OriginalName("E_NOT_PARTICIPATING")] ENotParticipating = 12,
    /// <summary>
    /// connect 시 잘못된 토큰일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_TOKEN")] EInvalidToken = 100,
    /// <summary>
    /// enter 시 잘못된 룸타입일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_ROOM_TYPE")] EInvalidRoomType = 110,
    /// <summary>
    /// enter 시 잘못된 룸ID일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_ROOM_ID")] EInvalidRoomId = 111,
    /// <summary>
    /// enter 시 칩(골드) 부족할 때
    /// </summary>
    [pbr::OriginalName("E_NOT_ENOUGH_CHIP")] ENotEnoughChip = 112,
    /// <summary>
    /// enter 시 잘못된 바이인 금액일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_BUY_IN")] EInvalidBuyIn = 113,
    /// <summary>
    /// enter 시 테이블에 이미 입장된 상태일 때
    /// </summary>
    [pbr::OriginalName("E_PLAYER_ALREADY_EXISTS")] EPlayerAlreadyExists = 114,
    /// <summary>
    /// enter 시 모든 테이블에 자리가 없을 때
    /// </summary>
    [pbr::OriginalName("E_NO_EMPTY_TABLE")] ENoEmptyTable = 115,
    /// <summary>
    /// enter 시 모든 좌석에 자리가 없을 때
    /// </summary>
    [pbr::OriginalName("E_NO_EMPTY_CHAIR")] ENoEmptyChair = 116,
    /// <summary>
    /// enter 시 손실한도 초과 시
    /// </summary>
    [pbr::OriginalName("E_LOSS_LIMIT")] ELossLimit = 117,
    /// <summary>
    /// action 시 진행 중인 베팅라운드가 없을 때
    /// </summary>
    [pbr::OriginalName("E_NO_ACTIVE_BETTING_ROUND")] ENoActiveBettingRound = 130,
    /// <summary>
    /// action 시 잘못된 액션일 때(amount가 잘못된 경우 포함)
    /// </summary>
    [pbr::OriginalName("E_INVALID_ACTION")] EInvalidAction = 131,
    /// <summary>
    /// 추방 투표 시 아직 플레이수가 부족할 때
    /// </summary>
    [pbr::OriginalName("E_CANNOT_VOTE")] ECannotVote = 140,
    /// <summary>
    /// 추방 투표 시 대상 유저가 테이블에 없을 때
    /// </summary>
    [pbr::OriginalName("E_CANDIDATE_NOT_IN_TABLE")] ECandidateNotInTable = 141,
    /// <summary>
    /// draw 시 진행 중인 교환라운드가 없을 때
    /// </summary>
    [pbr::OriginalName("E_NO_ACTIVE_DRAW_ROUND")] ENoActiveDrawRound = 150,
    /// <summary>
    /// draw 시 잘못된 교환 요청일 때
    /// </summary>
    [pbr::OriginalName("E_INVALID_DRAW")] EInvalidDraw = 151,
  }

  /// <summary>
  /// 게임 action 타입
  /// </summary>
  public enum ActionType {
    [pbr::OriginalName("AT_NONE")] AtNone = 0,
    [pbr::OriginalName("AT_FOLD")] AtFold = 1,
    [pbr::OriginalName("AT_CHECK")] AtCheck = 2,
    /// <summary>
    /// 아무도 베팅하지 않았을 때
    /// </summary>
    [pbr::OriginalName("AT_BET")] AtBet = 3,
    /// <summary>
    /// 기존 베팅과 동일하게 칩을 낼 때
    /// </summary>
    [pbr::OriginalName("AT_CALL")] AtCall = 4,
    /// <summary>
    /// 기존 베팅보다 더 낼 때
    /// </summary>
    [pbr::OriginalName("AT_RAISE")] AtRaise = 5,
    /// <summary>
    /// 전부 걸 때
    /// </summary>
    [pbr::OriginalName("AT_ALLIN")] AtAllin = 6,
  }

  public enum BetSizeType {
    [pbr::OriginalName("BS_NONE")] BsNone = 0,
    [pbr::OriginalName("BS_FOLD")] BsFold = 1,
    [pbr::OriginalName("BS_CHECK")] BsCheck = 2,
    [pbr::OriginalName("BS_BBING")] BsBbing = 3,
    [pbr::OriginalName("BS_CALL")] BsCall = 4,
    [pbr::OriginalName("BS_DDADANG")] BsDdadang = 5,
    [pbr::OriginalName("BS_QUATER")] BsQuater = 6,
    [pbr::OriginalName("BS_HALF")] BsHalf = 7,
    [pbr::OriginalName("BS_ALLIN")] BsAllin = 8,
    [pbr::OriginalName("BS_MAX")] BsMax = 9,
    [pbr::OriginalName("BS_END")] BsEnd = 10,
  }

  /// <summary>
  /// 추방 사유
  /// </summary>
  public enum KickReason {
    [pbr::OriginalName("KR_NONE")] KrNone = 0,
    /// <summary>
    /// 추방 투표
    /// </summary>
    [pbr::OriginalName("KR_VOTE")] KrVote = 1,
    /// <summary>
    /// 칩 부족
    /// </summary>
    [pbr::OriginalName("KR_CHIP")] KrChip = 2,
    /// <summary>
    /// 손실한도 도달
    /// </summary>
    [pbr::OriginalName("KR_LOSS")] KrLoss = 3,
    /// <summary>
    /// 점검
    /// </summary>
    [pbr::OriginalName("KR_MAINTENANCE")] KrMaintenance = 4,
    /// <summary>
    /// 비활성화
    /// </summary>
    [pbr::OriginalName("KR_INACTIVE")] KrInactive = 5,
    /// <summary>
    /// 연결 끊김
    /// </summary>
    [pbr::OriginalName("KR_DISCONNECT")] KrDisconnect = 6,
  }

  #endregion

  #region Messages
  public sealed partial class Error : pb::IMessage<Error> {
    private static readonly pb::MessageParser<Error> _parser = new pb::MessageParser<Error>(() => new Error());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Error> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Common.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error(Error other) : this() {
      code_ = other.code_;
      detail_ = other.detail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Error Clone() {
      return new Error(this);
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Common.ErrorCode code_ = global::Common.ErrorCode.EOk;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Common.ErrorCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "detail" field.</summary>
    public const int DetailFieldNumber = 2;
    private string detail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Detail {
      get { return detail_; }
      set {
        detail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Error);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Error other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Detail != other.Detail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Common.ErrorCode.EOk) hash ^= Code.GetHashCode();
      if (Detail.Length != 0) hash ^= Detail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != global::Common.ErrorCode.EOk) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Detail.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Detail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Common.ErrorCode.EOk) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Detail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Detail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Error other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Common.ErrorCode.EOk) {
        Code = other.Code;
      }
      if (other.Detail.Length != 0) {
        Detail = other.Detail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Common.ErrorCode) input.ReadEnum();
            break;
          }
          case 18: {
            Detail = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
